# Generated by Django 5.1.1 on 2024-10-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wedding_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wedding_gallery/')),
                ('description', models.CharField(max_length=255)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='wedding_api.wedding')),
            ],
        ),
    ]
