# Generated by Django 5.1.1 on 2024-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='wedding/invations/qr/'),
        ),
    ]
