# Generated by Django 5.1.1 on 2024-10-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('subscription', '0002_remove_tariffplan_duration_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tariff_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.tariffplan'),
        ),
    ]
