# Generated by Django 5.1.1 on 2024-10-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wedding_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('qr_code', models.CharField(max_length=255)),
                ('is_attending', models.BooleanField(default=False)),
                ('invite_link', models.URLField(blank=True, null=True)),
                ('total_donations', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='wedding_api.wedding')),
            ],
        ),
    ]
